version: '3.4'

services:

  mysql_server:
    build: ./docker-mysql/
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=restaurantappdb
      - MYSQL_USER=user_gourmet
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_HOST=%
      - TZ=America/Bogota
    volumes:
      - ./docker-mysql/scripts-mysql/:/docker-entrypoint-initdb.d/
    ports:
      - "3310:3306"
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend

  gourmetapp:
    build: ./
    image: gourmetapp
    environment:
      - host=mysql_server
      - username=user_gourmet
      - password=123456
      - TZ=America/Bogota
    depends_on:
      - mysql_server
    ports:
      - "8080:8080"
    restart: on-failure
    entrypoint: dockerize -wait tcp://mysql_server:3306 -timeout 10m java -jar /workspace/app.jar
    networks:
      - backend

volumes:
  my-data:

networks:
  backend: